--- 
title: "American Univeristy STAT 412-612"
author: "Kelsey Gonazlez"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "A course that teaches the basics of programming using the open source statistical program R. Imputing data, performing basic analysis, graphing, data types, control structures and functions in R. Most of the course will use the tidyverse packages in R and will rely on the RStudio IDE."

---

# Course description
The basics of programming using the open source statistical program R. Imputing data, performing basic analysis, graphing, data types, control structures and functions in R. Most of the course will use the tidyverse packages in R and will use the RStudio IDE.

# Course Learning Outcomes
Upon successful completion of this course, you will be able to:

* Produce reproducible research using R Markdown using relative paths
* Write basic R programs using control and data structures
* Use ggplot2 to visualize and understand both categorical and quantitative data
* Perform analysis on datasets using dplyr verbs select, mutate, filter, arrange, group_by and summarize
* Import data from csv files into R using readr
* Distinguish a tidy dataset from one that is not tidy. Use tidyr to make datasets tidy.
* Combine datasets using dplyr verbs for data joining
* Use regular expressions and stringr to manipulate character strings
* Reset levels of factor variables
* Communicate results of your data analysis

# How to approach the course
As you go through the lecture notes, the tasks for you to complete will be contained within the document. These tasks will constitute your homework assignment for that module of the course.

Pay attention on Canvas for the due dates for each assignment.

Each section will have a reading here, an in-class lecture and lab, and assignments to do. I expect that you code live with me as I show each example to understand the code and raise issues as they occur. Type each command into R yourself as I do it. Your fingers entering the commands will help you to learn them.

The material in the course is meant to borrow heavily from the course textbook, R for Data Science by Wickham and Grolemund. Most of the examples are taken directly from the book.

<!-- # Course Syllabus / Office hours / What’s on Blackboard -->
<!-- The course syllabus is available on your Blackboard course site or here. -->

<!-- I will have office hours on Zoom on Mondays at 10:45 - 11:30 am, 4:00 - 4:45 pm and 7:00 - 8:00 pm. Please come to at least one office hour per week and plan to have your video camera turned on so I can see you. -->

<!-- You will find places to upload your assignments on Blackboard. Your grades will also be on Blackboard along with course announcements. -->